plugins {
    id 'com.android.library'
    id 'com.android.legacy-kapt'
}

android {
    compileSdk = libs.versions.compileSdkVersion.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.minSdkVersion.get().toInteger()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            // Let the app module take care of this
            minifyEnabled false
        }
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig true
        resValues true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlin {
        jvmToolchain(21)
    }
    namespace 'com.thewizrd.shared_resources'
    lint {
        targetSdk libs.versions.targetSdkVersion.get().toInteger()
    }
    testOptions {
        targetSdk libs.versions.targetSdkVersion.get().toInteger()
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    // Unit Testing
    androidTestImplementation libs.test.core

    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation libs.test.runner
    androidTestImplementation libs.test.rules

    // Assertions
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.truth
    androidTestImplementation libs.google.truth

    // Kotlin
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.play.services
    implementation libs.core.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.recyclerview

    implementation libs.appcompat

    implementation libs.play.services.wearable

    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
    implementation libs.firebase.crashlytics
    implementation libs.firebase.config

    implementation libs.timber
    implementation libs.gson
}
